---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: _portfolio
  label: Portfolio - ADD NEW PROJECTS HERE
  create: all
  match: "**/*"
- type: jekyll-pages
  label: Structure - NO EDITING
  create: all
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
